## Numpy Assigment

**Into how many combination of 3D shape, a numpy array of size 96 can be reshaped?**

**Ans:** 65 (Brute force)

In [1]:
# Only for viewing csv data in better form.
# Can be used for reference and comparing results.
import pandas as pd
df = pd.read_csv('heart-disease.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [2]:
import numpy as np

#### 1. Load CSV File:
Load the CSV file using csv reader into a numpy array. Also convert each value to numerical.

In [3]:
from csv import reader

with open('heart-disease.csv', 'r') as file:
    raw_data = np.array(list(reader(file)))
    
raw_data_without_column = raw_data[1:] 
final_data = raw_data_without_column.astype('float32')
print(final_data)
print(final_data.shape)

[[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]
(303, 14)


#### 2. Extract Specific Columns:
Extract columns `age`, `chol`, and `thalach` from the CSV file and store them in a numpy array.

In [4]:
age_chol_thalach = final_data[:, [0, 4, 7]]
age_chol_thalach

array([[ 63., 233., 150.],
       [ 37., 250., 187.],
       [ 41., 204., 172.],
       [ 56., 236., 178.],
       [ 57., 354., 163.],
       [ 57., 192., 148.],
       [ 56., 294., 153.],
       [ 44., 263., 173.],
       [ 52., 199., 162.],
       [ 57., 168., 174.],
       [ 54., 239., 160.],
       [ 48., 275., 139.],
       [ 49., 266., 171.],
       [ 64., 211., 144.],
       [ 58., 283., 162.],
       [ 50., 219., 158.],
       [ 58., 340., 172.],
       [ 66., 226., 114.],
       [ 43., 247., 171.],
       [ 69., 239., 151.],
       [ 59., 234., 161.],
       [ 44., 233., 179.],
       [ 42., 226., 178.],
       [ 61., 243., 137.],
       [ 40., 199., 178.],
       [ 71., 302., 162.],
       [ 59., 212., 157.],
       [ 51., 175., 123.],
       [ 65., 417., 157.],
       [ 53., 197., 152.],
       [ 41., 198., 168.],
       [ 65., 177., 140.],
       [ 44., 219., 188.],
       [ 54., 273., 152.],
       [ 51., 213., 125.],
       [ 46., 177., 160.],
       [ 54., 304., 170.],
 

#### 3. Filtering Data:
Filter the rows where `sex` is `male` and `age` is greater than 50.

In [5]:
male_greater_than_50 = final_data[(final_data[:, 1] == 1) & (final_data[:, 0] > 50)]
male_greater_than_50

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [56.,  1.,  1., ...,  0.,  2.,  1.],
       [57.,  1.,  0., ...,  0.,  1.,  1.],
       ...,
       [59.,  1.,  0., ...,  2.,  1.,  0.],
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.]], dtype=float32)

#### 4. Compute Statistics:
Compute the mean and standard deviation of the `trestbps` column.

In [6]:
mean = np.mean(final_data[:, 3])
std_deviation = np.std(final_data[:, 3])
mean, std_deviation

(131.62376, 17.509178)

#### 5. Sorting Data:
Sort the data based on the `thalach` column in descending order.

In [7]:
sorted_indices = np.argsort(final_data[:, 7])[::-1] 
sorted_data_on_thalach = final_data[sorted_indices]
sorted_data_on_thalach

array([[29.,  1.,  1., ...,  0.,  2.,  1.],
       [54.,  1.,  1., ...,  1.,  3.,  0.],
       [42.,  1.,  2., ...,  0.,  3.,  1.],
       ...,
       [59.,  1.,  0., ...,  2.,  1.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [67.,  1.,  0., ...,  0.,  2.,  0.]], dtype=float32)

#### 6. Writing to CSV:
Write the filtered data from **Question 3** to a new CSV file named `"filtered_data.csv"`.

In [8]:
from csv import writer

with open('filtered_data.csv', 'w', newline='') as file:
    csv_writer = writer(file)
    csv_writer.writerows(male_greater_than_50)

#### 7. Conditional Counting:
Count the number of male and female from `sex` column.

In [9]:
male_count = np.sum(final_data[:, 1])
female_count = final_data.shape[0] - male_count
male_count, female_count

(207.0, 96.0)

#### 8. Conditional Filtering:
Filter the rows where `thal` (thalassemia) is 2 or 3.

In [10]:
thal_filtered_rows = final_data[(final_data[:, 12] == 2) | (final_data[:, 12] == 3)]
thal_filtered_rows

array([[37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       [56.,  1.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]], dtype=float32)

### Broadcasting:
Given two arrays A and B of shapes (3, 2) and (1, 2) respectively, perform element-wise addition using broadcasting.

In [11]:
A = np.random.randint(0, 9, (3, 2))
B = np.random.randint(0, 9, (1, 2))
print(A, end='\n\n')
print(B, end='\n\n')
print(A + B)

[[4 4]
 [1 6]
 [2 6]]

[[5 8]]

[[ 9 12]
 [ 6 14]
 [ 7 14]]


### Dot Product:
Compute the dot product of two matrices A (shape: 3x4) and B (shape: 4x2).

In [12]:
A = np.random.randint(0, 9, (3, 4))
B = np.random.randint(0, 9, (4, 2))

print(A, end='\n\n')
print(B, end='\n\n')

print(np.dot(A, B))

[[6 3 2 6]
 [0 6 7 2]
 [1 1 1 8]]

[[5 5]
 [4 0]
 [6 3]
 [3 7]]

[[72 78]
 [72 35]
 [39 64]]


### Sorting:
Sort the elements of a 1D array arr in descending order.

In [13]:
arr = np.random.randint(0, 9, 10)
print('arr: ',arr)

print('sorted: ',np.sort(arr)[::-1])

arr:  [7 2 7 6 7 0 8 6 0 5]
sorted:  [8 7 7 7 6 6 5 2 0 0]


### Counting:
Count the number of occurrences of a specific value in a 2D array 'arr'.

In [14]:
arr = np.random.randint(0, 9, (3, 4))
print(arr, end='\n\n')

print('Total number of 3 in arr: ', np.count_nonzero(arr == 3))
unique, total = np.unique(arr, return_counts=True)
print('\n Total number for each number (number, counts): \n', list(zip(unique, total)))

[[2 5 5 7]
 [7 1 6 0]
 [5 8 6 7]]

Total number of 3 in arr:  0

 Total number for each number (number, counts): 
 [(0, 1), (1, 1), (2, 1), (5, 3), (6, 2), (7, 3), (8, 1)]


### Reshaping and Resizing:
Reshape a 1D array 'arr' of size 20 into a 2D array of shape (4, 5). Also resize it. Store them into variable and change one value in each case. Check original array and see the difference.

In [15]:
arr = np.random.randint(0, 9, 20)
print(arr, end='\n\n')

reshaped_arr = arr.reshape(4, 5)
print(reshaped_arr, end='\n\n')

resized_arr = np.resize(arr, (4, 5))
print(resized_arr, end='\n\n')

resized_arr[0, 0] = 100
print(arr, end='\n\n')

reshaped_arr[0, 0] = 96
print(arr)

[8 6 2 6 6 0 6 1 7 2 1 2 3 4 8 1 1 6 7 7]

[[8 6 2 6 6]
 [0 6 1 7 2]
 [1 2 3 4 8]
 [1 1 6 7 7]]

[[8 6 2 6 6]
 [0 6 1 7 2]
 [1 2 3 4 8]
 [1 1 6 7 7]]

[8 6 2 6 6 0 6 1 7 2 1 2 3 4 8 1 1 6 7 7]

[96  6  2  6  6  0  6  1  7  2  1  2  3  4  8  1  1  6  7  7]


### Flatten and Ravel:
Flatten a 2D array 'arr; into a 1D array. Also Ravel it. Also store them into variable and change one value in each case. Check original array and see the difference.

In [16]:
arr = np.random.randint(0, 9, (2, 3))
print(arr, end='\n\n')

flatten_arr = arr.flatten()
print(flatten_arr, end='\n\n')

ravel_arr = arr.ravel()
print(ravel_arr, end='\n\n')

flatten_arr[0] = 100
print(arr, end='\n\n')

ravel_arr[0] = 96
print(arr)

[[4 5 5]
 [6 0 8]]

[4 5 5 6 0 8]

[4 5 5 6 0 8]

[[4 5 5]
 [6 0 8]]

[[96  5  5]
 [ 6  0  8]]


### View and Copy:
Create a view of a 2D array 'arr' and modify one of its elements. Check if the original array is modified.

In [17]:
arr = np.random.randint(0, 9, (2, 3))
print(arr, end='\n\n')

arr_view = arr.view()
print(arr_view, end='\n\n')

arr_view[0, 0] = 100
print(arr, end='\n\n')

[[1 8 6]
 [6 8 0]]

[[1 8 6]
 [6 8 0]]

[[100   8   6]
 [  6   8   0]]



### Indexing and Slicing:
Extract the first 3 rows and last 2 columns of a 2D array 'arr'.

In [18]:
arr = np.random.randint(0, 9, (4, 5))
print(arr, end='\n\n')

print(arr[:3, -2:])

[[7 3 5 0 4]
 [7 4 7 6 7]
 [8 2 1 8 1]
 [2 8 1 4 6]]

[[0 4]
 [6 7]
 [8 1]]


### Element-wise Operations:
Compute the square root of each element in a 2D array 'arr'.

In [19]:
arr = np.random.randint(0, 9, (3, 4))
print(arr, end='\n\n')

print(np.sqrt(arr))

[[7 5 6 0]
 [0 3 1 0]
 [4 6 7 0]]

[[2.64575131 2.23606798 2.44948974 0.        ]
 [0.         1.73205081 1.         0.        ]
 [2.         2.44948974 2.64575131 0.        ]]


### Statistical Operations:
Compute the mean, median, and standard deviation of a 2D array 'arr'.

In [20]:
arr = np.random.randint(0, 9, (3, 4))
print(arr, end='\n\n')

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

[[0 4 0 3]
 [5 2 6 1]
 [0 4 2 0]]

2.25
2.0
2.0463381929681126


### Boolean Indexing:
Select elements from a 1D array 'arr' that are greater than a certain threshold.

In [21]:
arr = np.random.randint(0, 9, 10)
print(arr, end='\n\n')

print(arr[arr > 5])

[4 7 7 3 3 1 8 8 1 8]

[7 7 8 8 8]


### Concatenation:
Concatenate two arrays A and B horizontally.

In [22]:
A = np.random.randint(0, 9, 5)
print(A, end='\n\n')

B = np.random.randint(0, 9, 5)
print(B, end='\n\n')

print(np.concatenate((A, B), axis=0))

[5 0 4 8 6]

[0 2 2 8 0]

[5 0 4 8 6 0 2 2 8 0]


### Unique Elements:
Find the unique elements in a 1D array 'arr'.

In [23]:
arr = np.random.randint(0, 9, 10)
print(arr, end='\n\n')

print(np.unique(A))

[8 3 7 8 5 7 8 4 6 5]

[0 4 5 6 8]


### Transpose:
Transpose a 2D array 'arr'.

In [24]:
arr = np.random.randint(0, 9, (2, 3))
print(arr, end='\n\n')

print(arr.T)

[[7 7 3]
 [4 0 8]]

[[7 4]
 [7 0]
 [3 8]]


### Matrix Inversion:
Compute the inverse of a square matrix A.

In [25]:
A = np.random.randint(0, 9, (3, 3))
print(A, end='\n\n')

print(np.linalg.inv(A))

[[0 2 2]
 [4 1 7]
 [6 8 1]]

[[-0.4296875  0.109375   0.09375  ]
 [ 0.296875  -0.09375    0.0625   ]
 [ 0.203125   0.09375   -0.0625   ]]


### Cumulative Sum:
Compute the cumulative sum of elements along a specified axis in a 2D array 'arr'.

In [26]:
arr = np.random.randint(0, 9, (4, 3))
print(arr, end='\n\n')

print('Cumulative sum along x-axis: ')
print(np.sum(arr, axis=0, keepdims=True), end='\n\n')

print('Cumulative sum along y-axis: ')
print(np.sum(arr, axis=1, keepdims=True))

[[4 8 0]
 [4 5 5]
 [2 7 1]
 [7 3 1]]

Cumulative sum along x-axis: 
[[17 23  7]]

Cumulative sum along y-axis: 
[[12]
 [14]
 [10]
 [11]]


### Set Operations:
Perform union, intersection, and difference of two 1D arrays A and B.

In [27]:
A = np.random.randint(0, 20, 8)
print(A, end='\n\n')

B = np.random.randint(0, 20, 8)
print(B, end='\n\n')

print('Union: ', np.union1d(A, B), end='\n\n')

print('Intersection: ', np.intersect1d(A, B), end='\n\n')

print('Difference: ', np.setdiff1d(A, B), end='\n\n')

[ 6 16 19  9  4  3  3 19]

[ 8 14  7  6  0 16  5  3]

Union:  [ 0  3  4  5  6  7  8  9 14 16 19]

Intersection:  [ 3  6 16]

Difference:  [ 4  9 19]



### Random Sampling:
Generate a random sample of size 10 from a 1D array 'arr'.

In [28]:
A = np.random.randint(0, 20, 100)
print(A, end='\n\n')

random_sample = np.random.choice(A, size=20)
print(random_sample)

[ 9 10  1 17  0  6 14  5 17  9 15  0  9 10 19 16  5  3 17 12  2 19  9 19
 15 19 13  1 12 13 15  0  0  3  8  2 12 18 14  3  0 10  1 18  4 15 14  7
  0  9 16  2  8 14 10 14  1  6  6 11  4 16 12  2 13 16 10  2 13  3  5 15
 16  0 16  5  2 13  5 10 19 14 14  9 13  6 11 17  3 16 10 17  1 16  6  1
  2  4 13 16]

[10 17 13 12 19  8  1 16 16 15 18 16  0 14 13  0 11 15 16  6]
